---
title: "Fourth Revision"
author: "Lena"
format: docx
editor: visual
editor_options: 
  chunk_output_type: console
execute: 
  echo: false
  warning: false
---

Let us see what we have got

```{r}
library(tidyverse)
library(readxl)
library(gt)
library(gtsummary)
library(glue)
library(showtext)
font_add_google(name = "Noto Serif", family = "Noto serif")
showtext_auto()
combined <- read_excel("combined.xlsx")
```

## Summary

```{r}
combined %>% janitor::clean_names() %>% 
  summarise(Number = sum(n, na.rm = T),
            Total_length = round(mean(total_length_cm, na.rm = T),2),
            Weight = round(mean(weight_g, na.rm = T),2), 
            .by = c(local_name,english_name,species,family)) %>% 
  arrange(desc(Number)) %>% 
  select(species, english_name, everything()) %>% 
  gt() %>% 
  tab_header(title = "Species Composition of Catch")
```

## Juveniles

```{r}
juv <- read_excel("juv.xlsx") %>% janitor::clean_names() %>% 
  mutate(species = case_when(species == "Anguilla begalensis" ~ "Anguilla bengalensis",
                             species == "Anguilla bengalensis" ~ "Anguilla bengalensis",
                             species == "Anguilla mossaambica" ~ "Anguilla mossambica",
                             species == "Anguillla mossambica" ~ "Anguilla mossambica",
                             species == "Anguillla mossambica" ~ "Anguilla mossambica",
                             species == "Anguillla marmorata" ~ "Anguilla marmorata",
                             .default = species),
         season = if_else(season == "Dry", "Dry", "Wet"),
         site = glue("SBE {effort}"))

juv %>% select(species, life_stage) %>% 
  tbl_summary(by = life_stage) %>% 
  modify_header(label = "Species") %>% 
  modify_spanning_header(all_stat_cols() ~ "**Life Stage**") %>% as_gt()
```

## Temporal

### Elvers

```{r}
juv %>% filter(life_stage == "Elver") %>% select(month,species) %>% 
  tbl_cross(percent = "row") %>% add_p()

```

### Glass eels

```{r}
juv %>% filter(life_stage != "Elver") %>% select(month, species) %>% 
  tbl_cross(percent = "row") %>% add_p()
```

## Season

### Elvers

```{r}
juv %>% filter(life_stage == "Elver") %>% select(season, species) %>% 
  tbl_cross(percent = "row") %>% add_p()

```

### Glass eels

```{r}
juv %>% filter(life_stage != "Elver") %>% select(season, species) %>% 
  tbl_cross(percent = "row") %>% add_p()
```

## Sites

## Glass eels

```{r}
juv %>% 
  select(site, species) %>% 
  tbl_cross(percent = "row")
```

## Elvers

```{r}
juv %>% 
 filter(life_stage == "Elver") %>% 
  select(site, species) %>% 
  tbl_cross(percent = "row")
```

## Lunar

```{r}
juv %>% select(moon_phase, species) %>% 
  tbl_cross(percent = "row")
```

## Plot

### Elvers

```{r}
#| fig-width: 9
#| fig-height: 4
juv %>% #filter(life_stage == "Elver") %>% 
  ggplot(aes(site, tl_cm, fill = species)) + 
  stat_summary(geom = "bar", fun.data = "mean_se", position = "dodge") +
  stat_summary(geom = "errorbar", fun.data = "mean_se",position = "dodge") + 
  facet_wrap(~life_stage, scales = "free") +
  scale_fill_manual(values = c("gray", "gray30", "black")) +
  theme_classic(base_family = "Noto serif", base_size = 20) +
  labs(y = "Length (cm)", x = "Sampling Site") + theme(legend.position = "bottom")
```
